server:
  port: 6009

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: eureka1.com
  server:
    enable-self-preservation: false   		#禁用保护,默认true
    eviction-interval-timer-in-ms: 10000  	#清理间隔（默认是60*1000）
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
      #defaultZone: http://eureka2.com:6002/eureka/
      #defaultZone: http://localhost:6001/eureka/	#单机版
      #defaultZone: http://eureka2.com:6002/eureka/	#集群互相指向
    register-with-eureka: false 				#单机false,默认true
    fetch-registry: false				#单机false,默认true

#spring:
#  security:
#    user:
#      name: admin

#      password: 123
